### ISSUE TITLE
Why not export a string?

### ISSUE THREAD

**Issue by amio** [sindresorhus/word-list#1]
Just curious, I think export the whole txt file as string would be intuitive, is there some consideration for exporting the txt file path?

**Comment by sindresorhus** [comment]
The text file is huge and takes some time to load. I didn't want to make assumptions about how people want to load it. Some might want to read it all at once synchronously, some might want it async, some might want it as a stream, and some might want to only read parts of it.

**Comment by amio** [comment]
Thanks for explanation!
