### ISSUE TITLE
Any way to use this on a browser?

### ISSUE THREAD

**Issue by t8** [sindresorhus/word-list#3]
I'm attempting to use this list for the browser, but 'fs' is pretty much only compatible with node, not browser. 

I tried using `browserify-fs` and `brfs`, but none of these are working with this situation? 

It specifically does not like the line: const englishWords = fs.readFileSync(wordListPath, 'utf8').split('\n');

**Comment by kevva** [comment]
Depends on which tool you're using. If you're using `webpack`, then [`raw-loader`](https://github.com/webpack-contrib/raw-loader) would work. Looks like [`brfs`](https://github.com/browserify/brfs) should work if you're using `browserify`.

This is not created with browsers in mind so it's really not an issue with this module.
