### ISSUE TITLE
Missing one-letter words?

### ISSUE THREAD

**Issue by rileyjshaw** [sindresorhus/word-list#6]
Hi! I can look into making a PR, but first wanted to check if there's an intentional reason that the words "a" and "i" are excluded from this list?

Thanks for putting this library together, it's great!

**Comment by sindresorhus** [comment]
The word list is from a [word game](https://github.com/lorenbrichter/Words), so I guess because they're not useful there. What's your use-case?

**Comment by rileyjshaw** [comment]
Ah, got it!

The use-case is silly, [I threw something quick on Glitch if you're curious](https://garrulous-shampoo.glitch.me/). But the following is no problem:

```
const wordList = [...wordString.split('\n'), 'a', 'i'];
```

I just wanted to check if it was known / intentional behavior. Feel free to close if you don't think it's an issue :)
